### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by longkunxuluke** [tomer196/GUDI#2]
Hi, it seems the syntax in https://github.com/tomer196/GaUDI/blob/main/train_edm.py#L186 is incorrect, probably change it to `print("best_epoch=".format(best_epoch), "best_val_loss=".format(best_val_loss))`?

**Comment by tomer196** [comment]
This is a standard f-string formatting (see [link](https://builtin.com/data-science/python-f-string)). I think that if you use Python version 3.6 or above it should work.
Please let me know if you need any more help.

**Comment by longkunxuluke** [comment]
I am using 3.7.7 but there is still a syntax error. Anyway this should be good and please ignore the issue :)
